# Generated by Django 4.1.7 on 2023-03-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='usertype',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
