# Generated by Django 4.1.7 on 2023-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyImages',
            field=models.FileField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
