# Generated by Django 3.2.6 on 2024-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_property_propertyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertyImages',
        ),
        migrations.AddField(
            model_name='property',
            name='propertyImages1',
            field=models.FileField(default=1, upload_to='images1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='propertyImages2',
            field=models.FileField(default=1, upload_to='images2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='propertyImages3',
            field=models.FileField(default=1, upload_to='images3'),
            preserve_default=False,
        ),
    ]
